print('Love is not a thing to understand.')
print('Love is not a thing to feel.')
print ('Love is not a thing to give and receive.')
print ('Love is a thing only to become')
print ('And eternally be.')
